"""empty message

Revision ID: 23d2020d1687
Revises:
Create Date: 2019-09-30 18:05:02.691482

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "23d2020d1687"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("refresh_token", sa.String(length=300), nullable=True),
        sa.Column("access_token", sa.String(length=300), nullable=True),
        sa.Column("expires_in", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("access_token")
    # ### end Alembic commands ###
