"""empty message

Revision ID: 623e6284136d
Revises:
Create Date: 2019-09-30 19:09:17.782930

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "623e6284136d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_token",
        sa.Column("refresh_token", sa.String(length=300), nullable=False),
        sa.Column("access_token", sa.String(length=300), nullable=True),
        sa.Column("expires_in", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("refresh_token"),
    )
    op.create_table(
        "user",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    op.drop_table("access_token")
    # ### end Alembic commands ###
