"""empty message

Revision ID: ce65c41f6879
Revises: 
Create Date: 2019-10-03 23:46:18.091082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce65c41f6879'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=128), nullable=True),
    sa.Column('refresh_token', sa.String(length=300), nullable=True),
    sa.Column('access_token', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_table('deal',
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('deal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deal')
    op.drop_table('user')
    # ### end Alembic commands ###
